_wandb:
    value:
        cli_version: 0.18.2
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 55
            "2":
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
            "4": 3.8.20
            "5": 0.18.2
            "8":
                - 2
                - 5
            "12": 0.18.2
            "13": linux-x86_64
addaptadj:
    value: true
adjtype:
    value: doubletransition
batch_size:
    value: 64
data:
    value: data/SYNTHETIC_EASY
device:
    value: cuda:0
dropout:
    value: 0.3
env_flags:
    value:
        GWN_DIAG_MODE: self_and_neighbor
        GWN_USE_CHEBY: "0"
        GWN_USE_POWER: "0"
epochs:
    value: 10
gcn_bool:
    value: true
learning_rate:
    value: 0.001
nhid:
    value: 32
pred_length:
    value: 96
print_every:
    value: 50
randomadj:
    value: true
seq_length:
    value: 96
weight_decay:
    value: 0.0001
