_wandb:
    value:
        cli_version: 0.18.2
        m:
            - "1": train/loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch
              "6":
                - 3
              "7": []
            - "1": valid/loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": test/horizon_mae
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": test/horizon_rmse
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/rmse
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": valid/mape
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": valid/rmse
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": test/horizon
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": test/horizon_mape
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train/mape
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.8.20
        t:
            "1":
                - 55
            "2":
                - 55
            "3":
                - 2
                - 7
                - 13
                - 16
                - 23
                - 55
                - 61
                - 62
            "4": 3.8.20
            "5": 0.18.2
            "8":
                - 2
                - 5
            "12": 0.18.2
            "13": linux-x86_64
addaptadj:
    value: true
adjtype:
    value: doubletransition
batch_size:
    value: 64
data:
    value: data/SYNTHETIC_EASY
device:
    value: cuda:0
dropout:
    value: 0.5
env_flags:
    value:
        GWN_DIAG_MODE: neighbor
        GWN_USE_CHEBY: "0"
        GWN_USE_POWER: "0"
epochs:
    value: 50
gcn_bool:
    value: true
learning_rate:
    value: 0.001
nhid:
    value: 64
pred_length:
    value: 12
print_every:
    value: 50
randomadj:
    value: true
seq_length:
    value: 12
weight_decay:
    value: 0.0001
